---
- name: Update CentOS and Debian/Ubuntu Systems
  hosts: all
  become: yes
  tasks:
    - name: Update CentOS packages
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Update Debian/Ubuntu packages
      apt:
        upgrade: yes
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
